
version: '3.4'

services:
  dotnetruntime106507:
    container_name: dummy_api
    image: ${DOCKER_REGISTRY-}dotnetruntime106507
    build:
      context: .
      dockerfile: DotnetRuntime106507/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=824852ff-d2e2-4d41-9db5-413aa2e4f2a1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/DotnetRuntime106507.pfx
    volumes:
      - ./DotnetRuntime106507.pfx:/https/DotnetRuntime106507.pfx
    ports:
      - "44349:443"

  dotnetruntime106507client:
    container_name: dummy_client
    image: ${DOCKER_REGISTRY-}dotnetruntime106507client
    build:
      context: .
      dockerfile: DotnetRuntime106507_Client/Dockerfile
    environment:
      - API_HOST_PORT=<YourIp>:44349
    volumes:
      - ./dumps:/app/dumps:rw
